name: Devnet Build

on:
    pull_request:
      types: [closed]

env:
    AWS_REGION: ${{ vars.AWS_REGION }}
    REPO_URL: ${{ vars.ECR_REPO_URL }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    DOCKER_IMAGE: public.ecr.aws/k2w1w1n8/lime-public/devnet:latest

jobs:
    build-devnet:
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup AWS CLI credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.REPO_URL }}
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile.devnet
            push: true
            tags: ${{ env.DOCKER_IMAGE }}
            
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            
        - name: Install Hardhat dependencies
          working-directory: ./hardhat
          run: npm install
          
        - name: Start local devnet container
          run: |
            docker pull ${{ env.DOCKER_IMAGE }}
            docker run -d -p 8545:8545 -p 8546:8546 -p 8547:8547 -p 30303:30303 --name devnet-test ${{ env.DOCKER_IMAGE }}
            
        - name: Run Hardhat tests against devnet
          working-directory: ./hardhat
          run: npm run test